from __future__ import annotations

import warnings
from importlib import import_module

from .candidates import (
    CandidateDetails,
    CandidateFeedbackSummary,
    CandidateInterviewHistory,
    CandidateRegistration,
    CandidateSummary,
    CreateCandidateRequest,
    InterviewInvite,
    InviteCandidateRequest,
)
from .common import (
    ApiResponse,
    DeleteResult,
    ErrorDetail,
    PaginatedResponse,
    PaginationInfo,
    ResponseMeta,
)
from .feedback import CategoryScore, FeedbackDetails, FeedbackSummary, RecordingUrl, Transcript
from .interviews import (
    AddCriteriaRequest,
    AddQuestionRequest,
    AddSubquestionRequest,
    CategoryAverage,
    CompletionCounts,
    CreateInterviewRequest,
    CreateInterviewResult,
    CriteriaCreateResult,
    CriteriaDeleteResult,
    CriteriaUpdateResult,
    DocumentedInterviewLevel,
    DocumentedInterviewType,
    EvaluationCriterion,
    InterviewAnalytics,
    InterviewDetails,
    InterviewQuestion,
    InterviewSubquestion,
    InterviewSummary,
    InterviewVisibility,
    PerformanceLevel,
    PublishInterviewResult,
    QuestionCreateResult,
    QuestionDeleteResult,
    QuestionUpdateResult,
    ScoringGuide,
    SubquestionCreateResult,
    SubquestionDeleteResult,
    SubquestionUpdateResult,
    UpdateCriteriaRequest,
    UpdateInterviewRequest,
    UpdateQuestionRequest,
    UpdateSubquestionRequest,
)

__all__ = [
    "AddCriteriaRequest",
    "AddQuestionRequest",
    "AddSubquestionRequest",
    "ApiResponse",
    "CandidateDetails",
    "CandidateFeedbackSummary",
    "CandidateInterviewHistory",
    "CandidateRegistration",
    "CandidateSummary",
    "CategoryAverage",
    "CategoryScore",
    "CompletionCounts",
    "CriteriaCreateResult",
    "CriteriaDeleteResult",
    "CriteriaUpdateResult",
    "CreateCandidateRequest",
    "CreateInterviewRequest",
    "CreateInterviewResult",
    "DeleteResult",
    "DocumentedInterviewLevel",
    "DocumentedInterviewType",
    "ErrorDetail",
    "EvaluationCriterion",
    "FeedbackDetails",
    "FeedbackSummary",
    "InterviewAnalytics",
    "InterviewDetails",
    "InterviewInvite",
    "InterviewQuestion",
    "InterviewSubquestion",
    "InterviewSummary",
    "InterviewVisibility",
    "InviteCandidateRequest",
    "PaginatedResponse",
    "PaginationInfo",
    "PerformanceLevel",
    "PublishInterviewResult",
    "QuestionCreateResult",
    "QuestionDeleteResult",
    "QuestionUpdateResult",
    "RecordingUrl",
    "ResponseMeta",
    "ScoringGuide",
    "SubquestionCreateResult",
    "SubquestionDeleteResult",
    "SubquestionUpdateResult",
    "Transcript",
    "UpdateCriteriaRequest",
    "UpdateInterviewRequest",
    "UpdateQuestionRequest",
    "UpdateSubquestionRequest",
]

_WEBHOOK_COMPAT_EXPORTS = {
    "CandidateInvitedEventData",
    "CandidateInvitedWebhookPayload",
    "CreateWebhookRequest",
    "EvaluationGeneratedEventData",
    "EvaluationGeneratedWebhookPayload",
    "InterviewCompletedEventData",
    "InterviewCompletedWebhookPayload",
    "InterviewCreatedEventData",
    "InterviewCreatedWebhookPayload",
    "InterviewPublishedEventData",
    "InterviewPublishedWebhookPayload",
    "InterviewStartedEventData",
    "InterviewStartedWebhookPayload",
    "UnknownWebhookData",
    "UnknownWebhookPayload",
    "UpdateWebhookRequest",
    "WebhookCategoryScore",
    "WebhookCreateResult",
    "WebhookDelivery",
    "WebhookDetails",
    "WebhookEventType",
    "WebhookHeaders",
    "WebhookPayload",
    "WebhookTestResult",
    "parse_webhook_payload",
}


def __getattr__(name: str) -> object:
    if name not in _WEBHOOK_COMPAT_EXPORTS:
        raise AttributeError(f"module 'mukhtabir.models' has no attribute {name!r}")

    warnings.warn(
        f"Importing {name} from 'mukhtabir.models' is deprecated; import it from "
        "'mukhtabir.webhooks' instead.",
        DeprecationWarning,
        stacklevel=2,
    )
    return getattr(import_module("mukhtabir.webhooks"), name)
